config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"

  get "/planner", to: "pages#planner", as: "planner"
  resources :cities do
    collection do
      patch :sort
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, :country, presence: true

  has_many :city_trips
  has_many :trips, through: :city_trips

  def address
    "#{name}, #{country}"
  end

  geocoded_by :address
  after_validation :geocode
end

app/models/city_trip.rb
class CityTrip < ApplicationRecord
  belongs_to :city
  belongs_to :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :city_trips
  has_many :cities, through: :city_trips

  has_many :user_trips
  has_many :users, through: :user_trips
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_trips
  has_many :trips, through: :user_trips
end

app/models/user_trip.rb
class UserTrip < ApplicationRecord
  belongs_to :user
  belongs_to :trip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  def index
    @cities = City.order(:order)

    if @cities
      @markers = @cities.geocoded.map do |city|
        {
          id: city.id,
          lat: city.latitude,
          lng: city.longitude,
          info_window_html: render_to_string(partial: "shared/info_window", locals: {city: city})
        }
      end
    end
  end

  def show
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    @city.save

    respond_to do |format|
      if @city.save
        format.html { redirect_to cities_path, notice: "City was successfully created." }
        format.json { render json: @city, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    @city.update(city_params)
    redirect_to planner_path
  end

  def destroy
    @city.destroy
    redirect_to planner_path, status: :see_other
  end

  def sort
    params[:order].each_with_index do |id, index|
      City.where(id: id).update_all(order: index + 1)
    end

    head :ok
  end

  private

  def city_params
    params.require(:city).permit(:name, :country, :longitude, :latitude, :order)
  end

  def set_city
    @city = City.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end

  def planner
    @trip = Trip.first
    @cities = City.order(:order)

    if @cities
      @markers = @cities.geocoded.map do |city|
        {
          id: city.id,
          lat: city.latitude,
          lng: city.longitude,
          info_window_html: render_to_string(partial: "shared/info_window", locals: {city: city})
        }
      end
    end
  end

  def sort
    params[:order].each_with_index do |id, index|
      City.where(id: id).update_all(order: index + 1)
    end

    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/_city_form.html.erb
<%= simple_form_for(@city, wrapper: :tailwind_form) do |f| %>
  <%= f.input :name %>
  <%= f.input :country, as: :string %>
  <%= f.button :submit, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/cities/edit.html.erb
<%= render "city_form", city: @city %>

app/views/cities/index.html.erb
<div class="flex h-screen">
  <div style="width: 100%; height: 100%;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_MAP_API_KEY'] %>"
    data-map-is-planner-map-value=false>
  </div>
  <div class="mx-10 my-4 w-80 flex flex-col">
    <div data-controller="list-sort" data-list-sort-url-value="<%= sort_cities_path %>">
      <ul data-list-sort-target="list">
        <% @cities.each do |city| %>
          <li data-id="<%= city.id %>" class="cursor-grab active:cursor-grabbing my-2">
            <%= city.address %>
          </li>
        <% end %>
      </ul>
    </div>
    <%= link_to "Create new city", new_city_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 my-2 rounded text-center" %>
    <%= link_to "Back to Planner", planner_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 my-2 rounded text-center" %>
  </div>
</div>

app/views/cities/new.html.erb
<%= simple_form_for(@city, wrapper: :tailwind_form) do |f| %>
  <%= f.input :name %>
  <%= f.input :country, as: :string %>
  <%= f.button :submit, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/cities/show.html.erb
<h2><%= @city.name %></h2>
<p><%= @city.country %></p>
<%= link_to "Back to Cities", cities_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThePlanner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="parent-class">
      <%= render "shared/flashes" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<div class="bg-[url('/images/forest-road-above-2000px.jpg')] bg-no-repeat bg-cover bg-center text-white h-screen">
  <div class="container mx-auto px-5 flex flex-col justify-center h-full">
    <div class="mx-auto">
    <h1 class="font-bold text-4xl text-center my-10">The Travel Planner</h1>
    <div class="flex justify-center">
      <%= link_to "ENTER", planner_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" %>
    </div>
    </div>
  </div>
</div>

app/views/pages/planner.html.erb
<div class="h-screen flex">
  <div class="relative group flex flex-col justify-center w-10 hover:w-28 transition-all duration-1000 px-2 bg-gray-200 text-2xl text-center">
    <div class="absolute top-0 left-1/2 -translate-x-1/2 mx-auto translate-left-1/2 transition-opacity duration-1000 opacity-0 group-hover:opacity-100">
      <p class="mt-2">trips</p>
      <%= link_to planner_path do %>
        <%= icon "plane-alt", variant: "solid", class: "w-12 h-12 mt-4 hover:text-color-red" %>
      <% end %>
      <%= link_to planner_path do %>
        <%= icon "plane-alt", variant: "solid", class: "w-12 h-12 mt-4 hover:text-color-red" %>
      <% end %>
      <%= link_to "SO", destroy_user_session_path, data: { turbo_method: :delete, confirm: "Sign out really?" } %>
    </div>
    <div class="transition-opacity duration-1000 opacity-100 group-hover:opacity-0">
      <p>G</p>
      <p>L</p>
      <p>O</p>
      <p>B</p>
      <p>A</p>
      <p>L</p>
    </div>
  </div>
  <div class="flex flex-col justify-center w-10 hover:w-28 transition-all duration-1000 bg-gray-100 px-2 text-2xl text-center">
    <p>T</p>
    <p>R</p>
    <p>I</p>
    <p>P</p>
  </div>
  <div class="flex flex-col justify-between w-1/2 mx-4 mt-3 mb-4">
    <div data-controller="list-sort" data-list-sort-url-value="<%= sort_cities_path %>">
      <ul data-list-sort-target="list">
        <% @cities.each do |city| %>
          <li data-id="<%= city.id %>" class="flex justify-between w-100 cursor-grab active:cursor-grabbing my-2">
            <p><%= city.address %></p>
            <%= link_to "x", city_path(city), data: {turbo_method: :delete} %>
          </li>
          <p data-duration></p>
        <% end %>
      </ul>
    </div>
    <%= link_to "All Cities", cities_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded"%>
  </div>
  <div style="width: 100%; height: 100%;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_MAP_API_KEY'] %>"
    data-map-is-planner-map-value=true>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="relative flex justify-between px-3 py-3 mb-4 border rounded bg-teal-200 border-teal-300 text-teal-800 m-1" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="relative justify-between flex px-3 py-3 mb-4 border rounded bg-teal-200 border-teal-300 text-teal-800 m-1" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_info_window.html.erb
<h2><%= city.name %></h2>
<p><%= city.country %></p>